### ISSUE TITLE
ERROR when trying to open a simple .mdl  ( This Tool is Broken )   ERROR IS BELOW IN DESCRIPTION AND I ADDED THE FILE IN QUESTION

### ISSUE THREAD

**Issue by gamedev44** [danakt/web-hlmv#60]
Error: Unsupported version of the MDL file    react-dom.production.min.js:209
    at t.parseModel (modelDataParser.ts:166:11)
    at Renderer.tsx:69:52
    at Object.useMemo (react-dom.production.min.js:165:493)
    at t.useMemo (react.production.min.js:25:113)
    at Renderer.tsx:69:38
    at Yo (react-dom.production.min.js:153:146)
    at vs (react-dom.production.min.js:261:496)
    at lu (react-dom.production.min.js:246:199)
    at su (react-dom.production.min.js:246:128)
    at Ks (react-dom.production.min.js:239:172)
       es @ react-dom.production.min.js:209

Uncaught Error: Unsupported version of the         react-dom.production.min.js:123 
MDL file  

    at t.parseModel (modelDataParser.ts:166:11)
    at Renderer.tsx:69:52
    at Object.useMemo (react-dom.production.min.js:165:493)
    at t.useMemo (react.production.min.js:25:113)
    at Renderer.tsx:69:38
    at Yo (react-dom.production.min.js:153:146)
    at vs (react-dom.production.min.js:261:496)
    at lu (react-dom.production.min.js:246:199)
    at su (react-dom.production.min.js:246:128)
    at Ks (react-dom.production.min.js:239:172)

**Comment by gamedev44** [comment]
PLEASE FIX THIS ISSUE SOON

**Comment by Be1zebub** [comment]
ru tryin to upload source 1 model?
seems like this project supports only goldsrc models

**Comment by MesaBlack** [comment]
I tried putting in what I think is the mdl for Ivan the space biker and it gives me a white screen

**Comment by gamedev44** [comment]
after having used a bit some things worked some things didnt idk but i guess this is an issue dependant on the model and environment viewing it.
